name: Send Email

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: gabrieltomazibi10@gmail.com
          password: jymc vduu jhts ohsu
          subject: "Novo Push no Repositório"
          body: "Foi realizado um push no repositório. Verifique o código."
          to: "gabriieltomazini@gmail.com"
          from: "gabrieltomazibi10@gmail.com"
          secure: true
